### PR TITLE
ref #201: fix for setting prediction field

### PR DESCRIPTION
**Pull request by pnpritchard**

### CODE REVIEW

**Comment by hollinwilkins** [comment]
@pnpritchard This is great! Thank you for finding this bug. I'm wondering if you can think of any easy tests we can add to illustrate this bug and the fix? Also, have you looked through the MLeap-Core model to see if this will be an issue there as well?

Thank you again for the help

**Comment by pnpritchard** [comment]
@hollinwilkins You're right, the MLeap-Core model has the same issue when using DecisionTreeRegressionModel. I'll commit a fix for that and try working on a test as well. Also, do you use an IDE? I tried adding the sbt-idea plugin so I could use IntelliJ but it didn't work.

**Comment by hollinwilkins** [comment]
@pnpritchard I do use an IDE. Lots of people have trouble with using an IDE for some reason. Can you also post what errors you get when trying to load MLeap into your IDE so we can try to fix it?

Thank you!

**Comment by hollinwilkins** [comment]
Merging this PR in. Actual predictions coming back from decision trees/random forest classifiers are correct because we use probabilities instead of this prediction field directly. We should still have the prediction field be corrected by this PR.

Thanks for the catch!

**Pull request merged**
