### PR TITLE
Allow serialization format to be set in SimpleSparkSerializer

### PR DESCRIPTION
**Pull request by clocklear**
This simple PR allows the bundle serialization format to be set in `SimpleSparkSerializer`.  The default is Json, much like everywhere else, so the change is backwards compatible.

### CODE REVIEW

**Comment by clocklear** [comment]
I have not been able to test it, as we don't use the PySpark integration.  A cursory glance of the python code doesn't reveal any uses of `SimpleSparkSerializer`, am I missing something?

**Comment by hollinwilkins** [comment]
Here are the references from PySpark.

https://github.com/combust/mleap/blob/master/python/mleap/pyspark/spark_support.py#L36-L45

**Comment by hollinwilkins** [comment]
My only concern is that the method call won't work because there is an extra parameter now, even though it does have a default.

**Comment by clocklear** [comment]
I'll see if I can figure out how to (at very least) set a new param on the python side that defaults to Json.

**Comment by hollinwilkins** [comment]
@clocklear A suggestion for a safer change (no Python needed), add an entirely new method that takes a SerializationFormat as a parameter. Have the existing method call that one with a default of SerializationFormat.Json.

**Pull request merged**
