### PR TITLE
#111 Support Conversion of Product classes to DefaultLeapFrame

### PR DESCRIPTION
**Pull request by ancasarb**
Issue #111 - implement changes to support converting:
1. (case class) -> DefaultLeapFrame w/ 1 row
2. Seq(case class) -> DefaultLeapFrame w/ n rows
3. DefaultLeapFrame -> Seq(case class); for example a DefaultLeapFrame w/ 1 row gets converted to a Seq w/ 1 element and a DefaultLeapFrame w/n rows gets converted to a Seq w/ n elements

Followed the example from Spark (https://github.com/apache/spark/blob/master/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/ScalaReflection.scala) to extract constructor parameters from case classes.

### CODE REVIEW

**Comment by hollinwilkins** [comment]
Hey Anca,

This looks like a great first half of this ticket. I assigned it to you, let's target the 0.7.0 release to include it. We're releasing 0.6.0 this week and want to make 0.7.0 a quick release after.

**Comment by ancasarb** [comment]
Hey Hollin,

Sounds good to me, I've just updated the PR with the second half of ticket which covers the conversion from a DefaultLeapFrame to a Seq of case classes, changes are ready for the 0.7.0 release.

**Comment by hollinwilkins** [comment]
Hey this is great. I am going to put it in the 0.6.0 release. I want to take some time later today to look over everything before I merge it in though.

**Comment by ancasarb** [comment]
Cool, let me know if there are any changes needed :)

**Comment by ancasarb** [comment]
Hey @hollinwilkins, I've updated the branch with the latest master.

**Pull request merged**
