### PR TITLE
[Ready For Merge] Spark 2.3 Support

### PR DESCRIPTION
**Pull request by clocklear**
This PR updates the Spark dependency to `2.3.0` and ensures all existing functionality works and associated unit-tests pass.  As of writing, that is the case; all features present in latest version of MLeap are working.  ~~I have not yet added functionality for new transformers added in 2.3; that's my next goal.~~

Spark 2.3's `FeatureHasher` transformer is also included in this PR.

As always, comments and feedback are welcome.

### CODE REVIEW

**Comment by clocklear** [comment]
Also, and potentially controversially, starting with Spark 2.3, builds against Scala 2.10 are no longer published to Maven.  Now seems like a good a time as any to drop support for Scala 2.10, so I removed it from cross compile.

**Comment by hollinwilkins** [comment]
@clocklear This all looks good. Can you give a quick rundown of the ANN and MPC changes just so I understand what they were for?

**Comment by clocklear** [comment]
Certainly.  In Spark 2.3, `MultilayerPerceptronClassifier` now inherits from `ProbabilisticClassifier[Vector, MultilayerPerceptronClassifier, MultilayerPerceptronClassificationModel]` instead of `Predictor[Vector, MultilayerPerceptronClassifier, MultilayerPerceptronClassificationModel]`.  All `ProbabilisticClassificationModel`s produce three outputs:

- predicted labels as [[predictionCol]] of type `Double`
- raw predictions (confidences) as [[rawPredictionCol]] of type `Vector`
- probability of each class as [[probabilityCol]] of type `Vector`

The previous version of MPC only outputted `predictionCol`, so this was causing the associated Spark parity test to fail.  Enabling the two new outputs required updating the underlying ANN functions, so that's why they've been modified as well.

**Comment by hollinwilkins** [comment]
@clocklear These changes look good to me. If you give the thumbs up, I'll go ahead and merge.

**Comment by clocklear** [comment]
Thanks! I've almost got `FeatureHasher` implemented as well; when that is complete, we can merge.

**Comment by cappaberra** [comment]
@hollinwilkins, upon merge of this PR (thanks @clocklear for putting it together!), are you planning to cut a new MLeap release (e.g. 0.9.7)? Thanks!

**Comment by clocklear** [comment]
`FeatureHasher` is implemented and is passing the parity tests, but whew boy it was a journey.  @hollinwilkins, mind looking over the model and letting me know what you think?  Had to do some tricky things because the algorithm needs concept of all the required schema bits -- field name, it's type, it's shape, etc.

I have to step out for a couple of hours, but I can throw a few more tests in around the model itself and maybe a few other things.

**Comment by hollinwilkins** [comment]
@clocklear Looks like it was a journey with those murmur3 hashing cases. Will have a closer look at this later today. Thank you for this PR! A lot of people have been asking for 2.3 support.

**Comment by clocklear** [comment]
@hollinwilkins Assuming Travis gives the sign-off, this should be good to merge.

**Pull request merged**
