### PR TITLE
Better parallelization of scala tests

### PR DESCRIPTION
**Pull request by lucagiovagnoli**
I'm trying to get tests to run quicker by parallelizing most of the scala steps.

I think that I've hit some Travis timeout in this PR: https://github.com/combust/mleap/pull/708/files  and I'm trying to fix that. But also, who doesn't like faster test execution? :)

@talalryz for review

### CODE REVIEW

**Comment by lucagiovagnoli** [comment]
Example UI on master (w/ deploy stage) 
Screen Shot 2020-07-27 at 16 00 38

**Comment by talalryz** [comment]
this lgtm! I am surprised that the old shell scripts was running sbt test + tests for each package individually.
Do you know if there was any reason for that?

**Comment by lucagiovagnoli** [comment]
> this lgtm! I am surprised that the old shell scripts was running sbt test + tests for each package individually.
> Do you know if there was any reason for that?

Yeah `sbt +test` is not actually running all of the others (xgboost, benchmark etc.), so we need to keep that in.

**Comment by lucagiovagnoli** [comment]
@ancasarb do you think we can merge this? It's a nice quality of life improvement on test iteration speed

**Comment by lucagiovagnoli** [comment]
I've noticed these tests failing in #708 , so I reran them here without changing the code. Apparently something with travis changed cause these were passing and I haven't changed anything

**Review by ancasarb — APPROVED** [review]
lgtm! thank you!

**Pull request merged**
