### PR TITLE
Add undoLog cleanup around usages of scala.reflect.api.Types.TypeApi.<:<

### PR DESCRIPTION
**Pull request by alexholmes**
Scala has a [undolog issue](https://github.com/scala/bug/issues/8302) in `scala.reflect.api.Types.TypeApi.<:<` which can cause memory leaks. The MLeap codebase uses this function in [MleapReflection.scala](https://github.com/combust/mleap/blob/v0.19.0/mleap-core/src/main/scala/ml/combust/mleap/core/reflection/MleapReflection.scala).

We have encountered this memory leak when executing `Transformer.transform` at a high volume.

mleap-memory-leak

We are also able to reproduce this memory leak on the console:

```scala
scala> :require mleap-core_2.12-0.19.0.jar
scala> :require mleap-tensor_2.12-0.19.0.jar
scala> :paste
// Entering paste mode (ctrl-D to finish)

import ml.combust.mleap.core.reflection.MleapReflection

case class LargeFeatures(
                     a: String,
                     b: String,
                     c: String,
                     d: String,
                     e: String,
                     f: String,
                     g: String,
                     h: String,
                     i: List[String])

println("before: " + MleapReflection.universe.asInstanceOf[scala.reflect.runtime.JavaUniverse].undoLog.log.size)
for (_ <- 0 until 1000) {
  MleapReflection.extractConstructorParameters[LargeFeatures]
}
println("after: " + MleapReflection.universe.asInstanceOf[scala.reflect.runtime.JavaUniverse].undoLog.log.size)

// Exiting paste mode, now interpreting.

before: 0
after: 2000
```

Local tests were passing with this change, including the unit test added to verify the fix:

```bash
$ sbt "project mleap-core" test
...
[info] - doesn't accumulate memory
...
[info] Total number of tests run: 7627
[info] Suites: completed 66, aborted 0
[info] Tests: succeeded 7627, failed 0, canceled 0, ignored 0, pending 0
[info] All tests passed.
[success] Total time: 26 s, completed Mar 24, 2022 4:09:16 PM
```

### CODE REVIEW

**Comment by alexholmes** [comment]
The Travis Pyhton 3.6 build is passing, but the Python 3.7 build seems to fail [executing this command](https://app.travis-ci.com/github/combust/mleap/jobs/564644055#L1618).

```bash
[6247] /home/travis/build/combust/mleap/python$ /home/travis/virtualenv/python3.7.1/bin/python setup.py sdist --formats=zip --dist-dir /home/travis/build/combust/mleap/python/.tox/dist >.tox/log/GLOB-0.log
ERROR: invocation failed (exit code 1), logfile: /home/travis/build/combust/mleap/python/.tox/log/GLOB-0.log
[1620]()
================================== log start ===================================
[1621]()Traceback (most recent call last):
[1622]()  File "setup.py", line 22, in <module>
[1623]()    from setuptools import setup, find_packages
[1624]()  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/setuptools/__init__.py", line 18, in <module>
[1625]()    from setuptools.dist import Distribution
[1626]()  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/setuptools/dist.py", line 34, in <module>
[1627]()    from ._importlib import metadata
[1628]()  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/setuptools/_importlib.py", line 28, in <module>
[1629]()    disable_importlib_metadata_finder(metadata)
[1630]()  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/setuptools/_importlib.py", line 12, in disable_importlib_metadata_finder
[1631]()    import importlib_metadata
[1632]()  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 471, in <module>
[1633]()    __version__ = version(__name__)
[1634]()  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 438, in version
[1635]()    return distribution(package).version
[1636]()  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 411, in distribution
[1637]()    return Distribution.from_name(package)
[1638]()  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 179, in from_name
[1639]()    dists = resolver(name)
[1640]()  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 886, in find_distributions
[1641]()    found = self._search_paths(context.name, context.path)
[1642]()AttributeError: 'str' object has no attribute 'name'
[1643]()
[1644]()=================================== log end ====================================
```

When I try building locally with 3.7 this command seems to run fine:

```bash
[86168] /Users/aholmes/eng/mleap-github-clone/python$ /Users/aholmes/eng/mleap-github-clone/.venv/bin/python3 setup.py sdist --formats=zip --dist-dir .tox/dist >.tox/log/GLOB-0.log
package .tmp/package/1/mleap-0.20.0-SNAPSHOT.zip links to dist/mleap-0.20.0-SNAPSHOT.zip (/Users/aholmes/eng/mleap-github-clone/python/.tox)
```

Given the contents of this PR I'm not sure if the PR is contributing to the build failure. I wonder whether anyone has seen this build issue before and would have any pointers around how to fix?

**Review by jsleight — APPROVED** [review]
(I merged master into your branch, which fixed the build)

All lgtm, thanks for the contribution!

@ancasarb did you want to look at this too?

**Review by ancasarb — APPROVED** [review]
lgtm!

**Comment by alexholmes** [comment]
thank you both, much appreciated!

**Pull request merged**
