### PR TITLE
Serialize handleInvalid param of VectorIndexer into mleap model

### PR DESCRIPTION
**Pull request by WeichenXu123**
Serialize handleInvalid param of VectorIndexer into mleap model

### CODE REVIEW

**Comment by lucagiovagnoli** [comment]
I found lots of these Transformers with similar issues, where some parameter was not serialized. If we had more tests, we could ensure e2e correctness and find out more of these. I've started writing some Parity tests like these ones: https://github.com/combust/mleap/blob/502cbef25692c6362f1b785ea98ed5cbe0d05880/mleap-xgboost-runtime/src/test/scala/ml/combust/mleap/xgboost/runtime/XGBoostPredictorClassificationModelParitySpec.scala

It'd be great if you could add a few small ones for the code you added

**Comment by ancasarb** [comment]
@lucagiovagnoli same note here https://github.com/combust/mleap/pull/674#issuecomment-625475959 about the parity tests. :)

**Comment by ancasarb** [comment]
@WeichenXu123 this is throwing

```
error] /home/travis/build/combust/mleap/mleap-core/src/main/scala/ml/combust/mleap/core/feature/VectorIndexerModel.scala:8: object SparkException is not a member of package org.apache.spark
[error] import org.apache.spark.SparkException
[error]        ^
[error] one error found
```

Could you please take a look? Thank you!

**Comment by WeichenXu123** [comment]
@ancasarb Fixed. Thanks!

**Pull request merged**
