### PR TITLE
Add support for numpy numbers to be json serializable

### PR DESCRIPTION
**Pull request by trams**
The problem was discovered by running
https://github.com/combust/mleap-demo/blob/master/notebooks/airbnb-price-regression-scikit.ipynb

During a bundle serialization an object was constructed
to describe a model. This object for some reason contained numpy numbers
instead of python native integers.

Therefore it was not json serializable cause the type was not recognized

This patch adds support for numpy numbers for json serializer

### CODE REVIEW

**Comment by ancasarb** [comment]
@trams could you please give a bit more details on which transformer or part of the pipeline was having this issue for the airbnb example? thank you!

**Comment by hollinwilkins** [comment]
@ancasarb @trams Is there an update on this? Should we merge this in?

**Comment by ancasarb** [comment]
@hollinwilkins I was just trying to understand what the issue that's being fixed is. as far as i am aware, we can serialize and score the airbnb without any issues.

**Comment by ancasarb** [comment]
Closing this, due to inactivity, please re-open if it's still an issue.

**Pull request closed without merging**
