### PR TITLE
bump sbt-assembly to fix fat jar not working issue

### PR DESCRIPTION
**Pull request by zhxiaogg**
in an empty project with `mleap-databricks-runtime` dependency, the following code will fail:
```scala
val bytes = Array.emptyByteArray
val shape: DataShape = ml.bundle.DataShape.parseFrom(bytes)
```

with error message:
```
Symbol 'type scalapb.GeneratedMessageCompanion' is missing from the classpath.
This symbol is required by 'object ml.bundle.DataShape'.
Make sure that type GeneratedMessageCompanion is in your classpath and check for conflicting dependencies with `-Ylog-classpath`.
A full rebuild may help if 'DataShape.class' was compiled against an incompatible version of scalapb.
    val shape: DataShape = ml.bundle.DataShape.parseFrom(bytes)

value parseFrom is not a member of object ml.bundle.DataShape
    val shape: DataShape = ml.bundle.DataShape.parseFrom(bytes)
```

After some digging, I found this is due to shading of scalapb (which is a scala lib) was not supported by the previous sbt-assembly plugin. It has been fixed in an recently version of the plugin, see https://github.com/sbt/sbt-assembly/pull/393.

### CODE REVIEW

**Comment by zhxiaogg** [comment]
@ancasarb  do u mind help reviewing this pr? will appreciate for it.

**Comment by zhxiaogg** [comment]
@ancasarb  the test failure is not related to changes in this pr, I've submitted another pr to fix it, see https://github.com/combust/mleap/pull/746

**Review by ancasarb — APPROVED** [review]
looks good, thanks for the fix!

**Comment by zhxiaogg** [comment]
Thanks @ancasarb , is it possible to get a patch release for now, like 0.16.x? or maybe 0.17.0.

**Pull request merged**
