### PR TITLE
Prepare work for make a release with Spark 2.4.x

### PR DESCRIPTION
**Pull request by WeichenXu123**
Prepare work for make a release with Spark 2.4.x

### CODE REVIEW

**Comment by WeichenXu123** [comment]
After merging this PR, We can release a version mleap-1.6 compatible with spark 2.4.x, and next step to release a new version mleap compatible with spark 3.0.

@ancasarb @lucagiovagnoli WDYT ?

**Comment by WeichenXu123** [comment]
Gently ping @ancasarb @lucagiovagnoli WDYT ?

**Comment by ancasarb** [comment]
@WeichenXu123 Yes, doing a release with these changes sounds fine. Since we will be upgrading a major version of Spark, I would also like to get this PR https://github.com/combust/mleap/pull/645 merged into the Spark 2.4.5 release, Luca is currently working on some final changes about this feature. 

I am currently looking at also fixing a few transformer related issues, namely, https://github.com/combust/mleap/issues/648, https://github.com/combust/mleap/issues/603, https://github.com/combust/mleap/issues/601, https://github.com/combust/mleap/issues/521 as well as https://github.com/combust/mleap/issues/647 and https://github.com/combust/mleap/issues/638, to make sure the fixes won't require an immediate upgrade of Spark, as depending on the circumstances, that may be more or less straightforward.

I have a few models with which I will do some checks against as well this week, to make sure I don't see issues, once we have a candidate release.

**Comment by WeichenXu123** [comment]
@ancasarb 
I create a pr for #648 here:
https://github.com/combust/mleap/pull/673

**Comment by WeichenXu123** [comment]
@ancasarb What about merge this PR first and then create a branch for spark 2.4.x ? And then we can upgrade mleap to build with spark 3.0 and release a spark 3.0 compat version.
Fixing #648, #603, #601, #521 as well as #647 and #638 are minor issues and took time to fix, but it is important for mleap users to see a release version compat with spark 3.0.

**Comment by lucagiovagnoli** [comment]
The drawback of moving MLeap to Spark 3.0 so quickly is stability. Spark 3 is in PREVIEW state and it might take a while for MLeap to reach a stable compatible bug-free version. Another drawback is backward-compatibility: some companies might take a long time to ugprade to spark 3.0, so it'd be great to have MLeap maintenance on spark 2.4.x for some time.

One way to address this could be to spin off a 3.0 branch so that we can easily maintain MLeap for spark 3 and backport all fixes to MLeap 2.4.x (separate branches is what spark does).

**Comment by mengxr** [comment]
@ancasarb @lucagiovagnoli Could you create a spark-3.0 branch so we can make progress on Spark 3.0 support?

**Pull request merged**
